### ISSUE TITLE
Image to use to run docker-topo in gitlab CI

### ISSUE THREAD

**Issue by davidban77** [aristanetworks/eoscentral#2]
Hello,

First of all great repo and article [network-ci-part3](https://github.com/aristanetworks/eoscentral/tree/networkci-p3).

I am trying to follow up your examples git test project but having difficulties trying to pick or setup an image that can run docker-topo...

What I am trying so far if to build the image by using the `docker:git` base image and using `docker:dind` in `services` on the job build of `.gitlab-ci`.

 On that image I just install python3 and pip and try to run `docker-topo --create tests/docker-topo/some_topoligy.yaml` but i have the following error

```
$ docker-topo --create tests/data/docker/docker-topo/ceos_ring/ceos_ring.yaml
/usr/bin/docker-topo:669: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  t_yml = yaml.load(stream)
Traceback (most recent call last):
  File "/usr/bin/docker-topo", line 812, in <module>
    main()
  File "/usr/bin/docker-topo", line 752, in main
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/usr/bin/docker-topo", line 752, in <listcomp>
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/usr/bin/docker-topo", line 331, in start
    self._attach()
  File "/usr/bin/docker-topo", line 348, in _attach
    link.connect(self, interface)
  File "/usr/bin/docker-topo", line 636, in connect
    self.network.connect(device, interface)
  File "/usr/bin/docker-topo", line 565, in connect
    ns_fd = os.open('/proc/{}/ns/net'.format(device.pid), os.O_RDONLY) 
FileNotFoundError: [Errno 2] No such file or directory: '/proc/217/ns/net'
ERROR: Job failed: exit code 1
```
I believe that this alpine-based image is not good to run the docker-topo....

So I was wondering you can help out with some pointers on how to build that image?

Thanks!

**Comment by davidban77** [comment]
Nevermind, just saw the environment setup on the README... closing it
